# Generated by Django 5.2.6 on 2025-12-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teamworkapp', '0002_postcomment_postshare_postview_postanalytics_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=100)),
                ('view_count', models.BigIntegerField()),
                ('subscriber_count', models.BigIntegerField()),
                ('video_count', models.BigIntegerField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
