# Generated by Django 5.2.6 on 2025-12-09 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teamworkapp', '0003_youtubestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubestats',
            name='channel_Name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
