# Generated by Django 5.2.6 on 2025-12-17 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teamworkapp', '0006_facebooktoken1_pagestats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtubestats',
            options={'ordering': ['-fetched_at']},
        ),
        migrations.AlterUniqueTogether(
            name='youtubestats',
            unique_together={('fetched_at',)},
        ),
    ]
