# Generated by Django 5.2.6 on 2025-12-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teamworkapp', '0007_alter_youtubestats_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='youtubestats',
            options={'ordering': ['-date']},
        ),
        migrations.RenameField(
            model_name='youtubestats',
            old_name='channel_Name',
            new_name='channel_name',
        ),
        migrations.AlterUniqueTogether(
            name='youtubestats',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='youtubestats',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='youtubestats',
            name='fetched_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='youtubestats',
            name='subscriber_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='youtubestats',
            name='video_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='youtubestats',
            name='view_count',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='youtubestats',
            unique_together={('channel_id', 'date')},
        ),
    ]
