# Generated by Django 5.2.6 on 2025-12-17 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teamworkapp', '0008_alter_youtubestats_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacebookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=255)),
                ('app_secret', models.CharField(max_length=255)),
                ('page_id', models.CharField(max_length=100)),
                ('long_lived_user_token', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Facebook Configuration',
                'verbose_name_plural': 'Facebook Configuration',
            },
        ),
    ]
