# Generated by Django 5.2.6 on 2025-12-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teamworkapp', '0008_facebookconfig_facebooktoken1_pagestats'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubestats',
            name='date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
