# Generated by Django 4.2.26 on 2025-12-21 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teamworkapp', '0011_passwordresetotp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YouTubeStats',
        ),
    ]
