# Generated by Django 4.2.26 on 2025-12-22 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teamworkapp', '0012_delete_youtubestats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresetotp',
            options={'ordering': ['-created_at'], 'verbose_name': 'Password Reset OTP', 'verbose_name_plural': 'Password Reset OTPs'},
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_otps', to=settings.AUTH_USER_MODEL),
        ),
    ]
