# Generated by Django 4.2.26 on 2025-12-22 04:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Teamworkapp', '0013_alter_passwordresetotp_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresetotp',
            options={},
        ),
        migrations.AlterField(
            model_name='passwordresetotp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
