# Generated by Django 4.2.26 on 2025-12-22 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teamworkapp', '0014_alter_passwordresetotp_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pagestats',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='pagestats',
            name='fetched_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='pagestats',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
