# Generated by Django 4.2.25 on 2026-01-03 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teamworkapp', '0016_telegramchannel_tiktokprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='YouTubeChannel',
        ),
    ]
