# Generated by Django 4.2.25 on 2026-01-03 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teamworkapp', '0017_delete_youtubechannel'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('channel_id', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
